### PR TITLE
JSON objects are parsed as stdClass by default

### PR DESCRIPTION
**Pull request by peterpp**
Parsing as associative arrays can be configured by $assoc parameter.

### CODE REVIEW

**Comment by MAXakaWIZARD** [comment]
Thanks, @peterpp!

**Comment by MAXakaWIZARD** [comment]
@peterpp BTW, objects were parsed as associative arrays by default and this PR actually does the opposite - it allowes to parse them as objects.

**Comment by peterpp** [comment]
@MAXakaWIZARD Yes, I know. I my opinion, default behavior should by the same as in PHP function json_decode.

**Comment by MAXakaWIZARD** [comment]
@peterpp It will brake backward compatibility, so I am leaving it as assoc by default. I do not see any problem to pass additional argument to have items as objects.

**Comment by peterpp** [comment]
@MAXakaWIZARD OK, no problem.

**Pull request merged**
